package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MaterialExportAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterialExportAllPropertiesEquals(MaterialExport expected, MaterialExport actual) {
        assertMaterialExportAutoGeneratedPropertiesEquals(expected, actual);
        assertMaterialExportAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterialExportAllUpdatablePropertiesEquals(MaterialExport expected, MaterialExport actual) {
        assertMaterialExportUpdatableFieldsEquals(expected, actual);
        assertMaterialExportUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterialExportAutoGeneratedPropertiesEquals(MaterialExport expected, MaterialExport actual) {
        assertThat(expected)
            .as("Verify MaterialExport auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterialExportUpdatableFieldsEquals(MaterialExport expected, MaterialExport actual) {
        assertThat(expected)
            .as("Verify MaterialExport relevant properties")
            .satisfies(e -> assertThat(e.getCreationDate()).as("check creationDate").isEqualTo(actual.getCreationDate()))
            .satisfies(e -> assertThat(e.getExportDate()).as("check exportDate").isEqualTo(actual.getExportDate()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMaterialExportUpdatableRelationshipsEquals(MaterialExport expected, MaterialExport actual) {
        assertThat(expected)
            .as("Verify MaterialExport relationships")
            .satisfies(e -> assertThat(e.getProductionSite()).as("check productionSite").isEqualTo(actual.getProductionSite()));
    }
}
