package com.mycompany.myapp.domain;

import static com.mycompany.myapp.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ProductInventoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductInventoryAllPropertiesEquals(ProductInventory expected, ProductInventory actual) {
        assertProductInventoryAutoGeneratedPropertiesEquals(expected, actual);
        assertProductInventoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductInventoryAllUpdatablePropertiesEquals(ProductInventory expected, ProductInventory actual) {
        assertProductInventoryUpdatableFieldsEquals(expected, actual);
        assertProductInventoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductInventoryAutoGeneratedPropertiesEquals(ProductInventory expected, ProductInventory actual) {
        assertThat(expected)
            .as("Verify ProductInventory auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductInventoryUpdatableFieldsEquals(ProductInventory expected, ProductInventory actual) {
        assertThat(expected)
            .as("Verify ProductInventory relevant properties")
            .satisfies(e -> assertThat(e.getQuantityOnHand()).as("check quantityOnHand").isEqualTo(actual.getQuantityOnHand()))
            .satisfies(e -> assertThat(e.getInventoryMonth()).as("check inventoryMonth").isEqualTo(actual.getInventoryMonth()))
            .satisfies(e -> assertThat(e.getInventoryYear()).as("check inventoryYear").isEqualTo(actual.getInventoryYear()))
            .satisfies(e -> assertThat(e.getType()).as("check type").isEqualTo(actual.getType()))
            .satisfies(e -> assertThat(e.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(actual.getPrice()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductInventoryUpdatableRelationshipsEquals(ProductInventory expected, ProductInventory actual) {
        assertThat(expected)
            .as("Verify ProductInventory relationships")
            .satisfies(e -> assertThat(e.getProduct()).as("check product").isEqualTo(actual.getProduct()));
    }
}
