package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProductOrderDetailAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductOrderDetailAllPropertiesEquals(ProductOrderDetail expected, ProductOrderDetail actual) {
        assertProductOrderDetailAutoGeneratedPropertiesEquals(expected, actual);
        assertProductOrderDetailAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductOrderDetailAllUpdatablePropertiesEquals(ProductOrderDetail expected, ProductOrderDetail actual) {
        assertProductOrderDetailUpdatableFieldsEquals(expected, actual);
        assertProductOrderDetailUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductOrderDetailAutoGeneratedPropertiesEquals(ProductOrderDetail expected, ProductOrderDetail actual) {
        assertThat(expected)
            .as("Verify ProductOrderDetail auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductOrderDetailUpdatableFieldsEquals(ProductOrderDetail expected, ProductOrderDetail actual) {
        assertThat(expected)
            .as("Verify ProductOrderDetail relevant properties")
            .satisfies(e -> assertThat(e.getOrderCreationDate()).as("check orderCreationDate").isEqualTo(actual.getOrderCreationDate()))
            .satisfies(e -> assertThat(e.getQuantity()).as("check quantity").isEqualTo(actual.getQuantity()))
            .satisfies(e -> assertThat(e.getUnitPrice()).as("check unitPrice").isEqualTo(actual.getUnitPrice()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductOrderDetailUpdatableRelationshipsEquals(ProductOrderDetail expected, ProductOrderDetail actual) {
        assertThat(expected)
            .as("Verify ProductOrderDetail relationships")
            .satisfies(e -> assertThat(e.getOrder()).as("check order").isEqualTo(actual.getOrder()))
            .satisfies(e -> assertThat(e.getProduct()).as("check product").isEqualTo(actual.getProduct()));
    }
}
