package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProductReceiptAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductReceiptAllPropertiesEquals(ProductReceipt expected, ProductReceipt actual) {
        assertProductReceiptAutoGeneratedPropertiesEquals(expected, actual);
        assertProductReceiptAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductReceiptAllUpdatablePropertiesEquals(ProductReceipt expected, ProductReceipt actual) {
        assertProductReceiptUpdatableFieldsEquals(expected, actual);
        assertProductReceiptUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductReceiptAutoGeneratedPropertiesEquals(ProductReceipt expected, ProductReceipt actual) {
        assertThat(expected)
            .as("Verify ProductReceipt auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductReceiptUpdatableFieldsEquals(ProductReceipt expected, ProductReceipt actual) {
        assertThat(expected)
            .as("Verify ProductReceipt relevant properties")
            .satisfies(e -> assertThat(e.getCreationDate()).as("check creationDate").isEqualTo(actual.getCreationDate()))
            .satisfies(e -> assertThat(e.getPaymentDate()).as("check paymentDate").isEqualTo(actual.getPaymentDate()))
            .satisfies(e -> assertThat(e.getReceiptDate()).as("check receiptDate").isEqualTo(actual.getReceiptDate()))
            .satisfies(e -> assertThat(e.getStatus()).as("check status").isEqualTo(actual.getStatus()))
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductReceiptUpdatableRelationshipsEquals(ProductReceipt expected, ProductReceipt actual) {}
}
